#!/bin/bash

docker run \
 -i \
 --rm \
 --user $(id -u):$(id -g) \
 --env PWD=$PWD \
 --volumes-from disk \
 --volume /etc/passwd:/etc/passwd \
 --volume /etc/group:/etc/group \
 -w $PWD \
 apiki/node:1.1 \
 bash \
 -c "node $@"
