#!/bin/bash

docker run \
 -i \
 --rm \
 --user $(id -u):$(id -g) \
 --env PWD=$PWD \
 --volumes-from disk \
 --volume /etc/passwd:/etc/passwd \
 --volume /etc/group:/etc/group \
 -w $PWD \
 -p 8000:8000 \
 apiki/node:1.2 \
 serverless $@
