#!/bin/bash

docker run \
 -it \
 --rm \
 --user $(id -u):$(id -g) \
 --env PWD=$PWD \
 --volumes-from disk \
 --volume /etc/passwd:/etc/passwd \
 --volume /etc/group:/etc/group \
 -w $PWD \
 --network="devkit0" \
 -p 3000:3000 \
 apiki/node:1.1 \
 bash \
 -c "yarn $@"